import { Heroine } from "./heroine";

export const heroines: Heroine[] = [
  {
    fullName: "Людмила Колупаева, физик",
    name: "Людмила Колупаева",
    img_src: "./assets/images/kolupaeva/kolupaeva.jpg",
    images: {
      experiments: "./assets/images/kolupaeva/experiments.jpg",
      thumbs: ["./assets/images/kolupaeva/thumb_1.jpg",
        "./assets/images/kolupaeva/thumb_2.jpg",
        "./assets/images/kolupaeva/thumb_3.jpg",
        "./assets/images/kolupaeva/thumb_4.jpg"],
      images: ["./assets/images/kolupaeva/luda_9.jpg",
        "./assets/images/kolupaeva/luda_1.jpg",
        "./assets/images/kolupaeva/luda_2.jpg",
        "./assets/images/kolupaeva/luda_3.jpg",
        "./assets/images/kolupaeva/luda_4.jpg",
        "./assets/images/kolupaeva/luda_5.jpg",
        "./assets/images/kolupaeva/luda_6.jpg",
        "./assets/images/kolupaeva/luda_7.jpg",
        "./assets/images/kolupaeva/luda_8.jpg"]
    },
    interview: "UEjYvOtBMEI",
    youtube: "ZQzMCEtFoeY",
    collegues: "w6zh1yXZFWY",
    shortBiography: "<b>кандидат физико-математических наук</b><br>научный сотрудник ЛЯП ОИЯИ",
    biography: "<ul><li>Родилась в&nbsp;городе Озёрске Челябинской области.</li><li>Окончила МГУ им. М.&nbsp;В.&nbsp;Ломоносова по&nbsp;специальности физика атомного ядра и&nbsp;элементарных частиц.</li><li>В&nbsp;2021 году защитила диссертацию по&nbsp;теме &laquo;Анализ данных эксперимента NOvA с&nbsp;целью измерения параметров осцилляций нейтрино&raquo;.",
    interestInScience: "",
    familyAndWork: "",
    experiments: 'Кандидат физико-математических наук <b>Людмила Колупаева</b> закончила физический факультет МГУ в&nbsp;2017&nbsp;году, а&nbsp;уже в&nbsp;2021 защитила диссертацию по&nbsp;теме &laquo;Анализ данных эксперимента NOvA с&nbsp;целью измерения параметров осцилляций нейтрино&raquo;. Она научный сотрудник Сектора ускорительных нейтрино Научно-экспериментального отдела физики элементарных частиц ЛЯП ОИЯИ.<br><br>С&nbsp;2015 года участвует в ускорительном эксперименте NOvA по&nbsp;изучению осцилляций нейтрино (Fermilab, США), а&nbsp;с&nbsp;2020&nbsp;года&nbsp;&mdash; в&nbsp;международном ускорительном нейтринном эксперименте DUNE. Людмила&nbsp;&mdash; стипендиат конкурсов и&nbsp;премий для молодых учёных.',
    difficulties: "",
    hobbies: "Я&nbsp;люблю разного рода игровые виды спорта, где нужно состязаться, выигрывать. Потом настольные игры: у&nbsp;меня есть друзья, с&nbsp;которыми мы&nbsp;часто собираемся и&nbsp;играем &lt;...&gt;.<br><br>А&nbsp;еще я&nbsp;люблю читать.",
    wishes: 'Что посоветовать школьникам и&nbsp;студентам? Ну, конечно&nbsp;же, читать. Участвовать в&nbsp;разного рода стажировках, смотреть, как делается реальная наука. Не&nbsp;та, которая им&nbsp;преподается в&nbsp;вузах. Она, хотя и&nbsp;является необходимым базисом для любого физика, тем не&nbsp;менее часто запаздывает по&nbsp;сравнению с&nbsp;современной наукой, которая прямо сейчас делается в&nbsp;научных центрах. То&nbsp;есть в&nbsp;первую очередь попробовать себя именно в&nbsp;этой науке, а&nbsp;потом решать, нравится или нет.',
    time: {
      interestInScience: '',
      carierStart: '',
      familyAndWork: '',
      experiments: '',
      difficulties: '',
      hobbies: '00:34',
      perfectDay: '',
      wishes: '00:51',
    },
    timeCode: {
      interestInScience: '',
      carierStart: '566',
      familyAndWork: '',
      experiments: '1132',
      difficulties: '2372',
      hobbies: '2905',
      perfectDay: '3129',
      wishes: '3303',
    }
  },
  {
    fullName: "Ирина Титкова, физик",
    name: "Ирина Титкова",
    img_src: "./assets/images/titkova/titkova.jpg",
    images: {
      experiments: "./assets/images/titkova/experiments.jpg",
      thumbs: ["./assets/images/titkova/thumb_1.jpg",
        "./assets/images/titkova/thumb_2.jpg",
        "./assets/images/titkova/thumb_3.jpg",
        "./assets/images/titkova/thumb_4.jpg"],
      images: ["./assets/images/titkova/irina_9.jpg",
        "./assets/images/titkova/irina_1.jpg",
        "./assets/images/titkova/irina_2.jpg",
        "./assets/images/titkova/irina_3.jpg",
        "./assets/images/titkova/irina_4.jpg",
        "./assets/images/titkova/irina_5.jpg",
        "./assets/images/titkova/irina_6.jpg",
        "./assets/images/titkova/irina_7.jpg",
        "./assets/images/titkova/irina_8.jpg"]
    },
    interview: "fXp1LUS5owY",
    youtube: "ZQzMCEtFoeY",
    collegues: "wooNj9PNlEw",
    shortBiography: "<b>кандидат физико-математических наук</b><br>ученый секретарь ЛЯП ОИЯИ",
    biography: "<ul><li>Родилась в&nbsp;Дубне.</li><li>Окончила МФТИ по&nbsp;специальности прикладная математика и&nbsp;физика.</li><li>В&nbsp;2002 году защитила диссертацию по&nbsp;теме &laquo;Магнитная структура накопителя электронов со&nbsp;встроенным сильнополевым генератором излучения&raquo;.</li><li>Взрослая дочь.</li></ul>",
    interestInScience: "",
    familyAndWork: "<b>Ирине Титковой</b> с&nbsp;маленькой дочкой очень помогли родители: &laquo;У&nbsp;меня мама просто взялась сидеть с&nbsp;ребенком&raquo;.<br><br>Ирине очень много времени приходилось проводить в&nbsp;зарубежных командировках. А когда дочь подросла и&nbsp;бабушка не&nbsp;смогла справляться со&nbsp;своенравным подростком, пришлось отказаться от&nbsp;командировок и&nbsp;взять &laquo;в&nbsp;нагрузку&raquo; преподавание в&nbsp;университете. Теперь дочь выросла, стала талантливым программистом, работает в&nbsp;Google.",
    experiments: 'Кандидат физико-математических наук <b>Ирина Титкова</b> окончила МФТИ по&nbsp;специальности прикладная математика и&nbsp;физика. В&nbsp;2002 году защитила диссертацию по&nbsp;теме &laquo;Магнитная структура накопителя электронов со&nbsp;встроенным сильнополевым генератором излучения&raquo;.<br><br>С&nbsp;2009&nbsp;года и&nbsp;до&nbsp;настоящего времени Ирина&nbsp;&mdash; ученый секретарь ЛЯП ОИЯИ. В&nbsp;задачи ученого секретаря входят: подготовка материалов для&nbsp;годовых планов и&nbsp;научных отчетов Лаборатории; подготовка материалов для&nbsp;рассмотрения на&nbsp;сессиях Программно-консультативных комитетов и&nbsp;Ученого совета ОИЯИ; учёт выполненных и&nbsp;направленных для&nbsp;публикации научных работ и&nbsp;докладов; контроль правильности оформления работ и&nbsp;экспертных протоколов.',
    difficulties: "",
    hobbies: "У&nbsp;меня была мечта&nbsp;&mdash; лютня. И&nbsp;я&nbsp;нашла преподавателя&nbsp;&mdash; в&nbsp;Москве есть лютневая школа,&nbsp;&mdash; она мне посоветовала мастера. Семихорная лютня ко&nbsp;мне приехала из&nbsp;Пинска. И&nbsp;вот мы&nbsp;занимаемся через Zoom.<br><br>А&nbsp;еще у&nbsp;меня была детская мечта: я&nbsp;хотела сесть на&nbsp;мотоцикл. И&nbsp;я&nbsp;это сделала! Я&nbsp;получила права и&nbsp;даже попробовала себя в&nbsp;мотокроссе.",
    wishes: 'Важно понять, что ты&nbsp;хочешь, чем ты&nbsp;горишь. А&nbsp;дальше просто идти за&nbsp;своей мечтой. Когда человек горит, когда ему интересно, он&nbsp;может горы свернуть. Он&nbsp;будет не&nbsp;спать ночами, будет пилить, крутить, формулы писать. А&nbsp;если ему не&nbsp;интересно, то&nbsp;он&nbsp;не&nbsp;будет это делать ни&nbsp;в&nbsp;детском саду, ни&nbsp;в&nbsp;институте&nbsp;&mdash; никогда. Стакан наполовину пуст или наполовину полон. Надо посмотреть с&nbsp;оптимистичной стороны и&nbsp;сказать: &laquo;Всё, я&nbsp;хочу туда&raquo;. И&nbsp;идти туда. Разочарования будут. Дело не&nbsp;в&nbsp;том, что происходит, а&nbsp;в&nbsp;том, как ты&nbsp;на&nbsp;это смотришь. Если с&nbsp;полной стороны стакана, то: &laquo;Ну&nbsp;и&nbsp;ладно. И&nbsp;случилось. Хорошо. Точка роста. Пойду дальше&raquo;. Всё очень просто: не&nbsp;надо сразу ставить себе цель стать кем-то. Не&nbsp;сделать и&nbsp;стать, а&nbsp;делать и&nbsp;быть.',
    time: {
      interestInScience: '',
      carierStart: '',
      familyAndWork: '02:12',
      experiments: '',
      difficulties: '',
      hobbies: '01:42',
      perfectDay: '',
      wishes: '01:08',
    },
    timeCode: {
      interestInScience: '',
      carierStart: '429',
      familyAndWork: '851',
      experiments: '1191',
      difficulties: '2483',
      hobbies: '2802',
      perfectDay: '',
      wishes: '3503',
    }
  }, {
    fullName: "Галина Карамышева, физик",
    name: "Галина Анатольевна Карамышева",
    img_src: "./assets/images/karamysheva/karamysheva.jpg",
    images: {
      experiments: "./assets/images/karamysheva/experiments.jpg",
      thumbs: ["./assets/images/karamysheva/thumb_1.jpg",
        "./assets/images/karamysheva/thumb_2.jpg",
        "./assets/images/karamysheva/thumb_3.jpg",
        "./assets/images/karamysheva/thumb_4.jpg"],
      images: ["./assets/images/karamysheva/galina_9.jpg",
        "./assets/images/karamysheva/galina_1.jpg",
        "./assets/images/karamysheva/galina_2.jpg",
        "./assets/images/karamysheva/galina_3.jpg",
        "./assets/images/karamysheva/galina_4.jpg",
        "./assets/images/karamysheva/galina_5.jpg",
        "./assets/images/karamysheva/galina_6.jpg",
        "./assets/images/karamysheva/galina_7.jpg",
        "./assets/images/karamysheva/galina_8.jpg"]
    },
    interview: "uh95l_4Fkwg",
    youtube: "ZQzMCEtFoeY",
    collegues: "1TcDRzzLOVI",
    shortBiography: "<b>доктор физико-математических наук</b><br>начальник Научно-экспериментального отдела новых&nbsp;ускорителей",
    biography: "<ul><li>Родилась в&nbsp;Чернигове (Украина).</li><li>Окончила МИФИ.</li><li>В&nbsp;2001 году защитила кандидатскую диссертацию по&nbsp;теме &laquo;Динамика частиц в&nbsp;сильноточных циклотронах с&nbsp;пространственной вариацией поля&raquo;.</li><li>В&nbsp;2013&nbsp;году защитила докторскую диссертацию по&nbsp;теме &laquo;Разработка и&nbsp;оптимизация циклотронов для медицинских применений&raquo;.</li><li>В&nbsp;Научно-экспериментальном отделе новых ускорителей под руководством Галины Анатольевны ведутся разработки проектов циклотронов для протонной терапии.</li><li>Двое взрослых детей.</li></ul>",
    interestInScience: "У&nbsp;нас была самая сильная школа города. И&nbsp;мне повезло с&nbsp;учителем. Людмила Николаевна преподавала у&nbsp;меня всего один год. Но&nbsp;именно она и&nbsp;определила мой выбор. Она умела и&nbsp;любила решать задачи по&nbsp;физике, давала сложные задачи. А&nbsp;ребенку не&nbsp;так много нужно, совсем не&nbsp;обязательно его &laquo;тренировать&raquo;. Важно заинтересовать, показать.",
    familyAndWork: "<b>Галина Карамышева</b> считает, что если семья и&#160;руководство на&#160;стороне женщины, то&#160;в&#160;науке ей&#160;будет комфортнее, чем во&#160;многих других областях. Ей самой&#160;очень повезло: руководитель разрешал приходить на работу в&#160;вечернее время (в&#160;научной сфере вы&#160;можете не&#160;быть привязанной к&#160;какому-то строгому графику, как врач или учитель), а&#160;муж, приходя вечером с&#160;работы, брал на&#160;себя заботу о&#160;детях.",
    experiments: 'Доктор физико-математических наук, начальник Научно-экспериментального отдела новых ускорителей ЛЯП ОИЯИ <b>Галина Карамышева</b> закончила МИФИ. В&nbsp;2001 году защитила кандидатскую диссертацию по&nbsp;теме &laquo;Динамика частиц в&nbsp;сильноточных циклотронах с&nbsp;пространственной вариацией поля&raquo;, в&nbsp;2013 году&nbsp;&mdash; докторскую по&nbsp;теме &laquo;Разработка и&nbsp;оптимизация циклотронов для медицинских применений&raquo;.<br><br>С&nbsp;2005 года работала над проектом циклотрона С400, предназначенного для адронной терапии. C&nbsp;2016 года руководит разработкой проектов циклотронов для протонной терапии.<br><br>В&nbsp;настоящее время под руководством Г.&nbsp;А.&nbsp;Карамышевой разработан проект медицинского циклотрона MSC-230. Предстоит не&nbsp;только изготовить циклотрон, но&nbsp;и&nbsp;создать центр для медико-биологических исследований, в&nbsp;частности для изучения флэш-терапии&nbsp;&mdash; нового метода облучения ультракороткими мощными импульсами.',
    difficulties: "Я&nbsp;поехала в&nbsp;Дубну, несмотря на&nbsp;то, что меня предупреждали: девушку потом на&nbsp;работу всё равно не&nbsp;возьмут. Потому что конкуренция была высокая, могли выбирать. Конечно, выберут мальчика. Ну&nbsp;что там говорить, дети пойдут, а&nbsp;это на&nbsp;два-три года женщина выпадает из&nbsp;работы.",
    hobbies: "Наука&nbsp;&mdash; это и&nbsp;есть увлечение. Вот в&nbsp;этом её огромное преимущество. Это работа, которая делается с&nbsp;радостью. &lt;...&gt; Я&nbsp;люблю быть на&nbsp;природе, люблю купаться, плавать. &lt;...&gt; Я&nbsp;очень люблю, когда лето, когда солнце, когда море...",
    wishes: 'Важно, чтобы была мечта. Если есть эта мечта, есть желание, то&nbsp;для женщины занятие наукой&nbsp;&mdash; очень хорошая профессия! Даже возвращаться из&nbsp;декретного отпуска в&nbsp;науке удобно. Это во-первых. Во-вторых, это та&nbsp;профессия, которой ты&nbsp;можешь не&nbsp;прекращать заниматься, даже ухаживая за&nbsp;ребенком. Я&nbsp;не&nbsp;считаю, что наука&nbsp;&mdash; это какая-то более сложная профессия для женщины. Важно, независимо от&nbsp;того, женщина вы&nbsp;или мужчина, чтобы у&nbsp;вас было желание заниматься наукой, было умение изучать сложные дисциплины. А&nbsp;разочароваться в&nbsp;самой науке невозможно.',
    time: {
      interestInScience: '01:27',
      carierStart: '',
      familyAndWork: '02:26',
      experiments: '',
      difficulties: '',
      hobbies: '00:44',
      perfectDay: '',
      wishes: '01:13',
    },
    timeCode: {
      interestInScience: '107',
      carierStart: '',
      familyAndWork: '982',
      experiments: '1257',
      difficulties: '2067',
      hobbies: '2939',
      perfectDay: '',
      wishes: '3430',
    }
  }, {
    fullName: "Елена Кравченко, биолог",
    name: "Елена Кравченко",
    img_src: "./assets/images/kravchenko/kravchenko.jpg",
    images: {
      experiments: "./assets/images/kravchenko/experiments.jpg",
      thumbs: ["./assets/images/kravchenko/thumb_1.jpg",
        "./assets/images/kravchenko/thumb_2.jpg",
        "./assets/images/kravchenko/thumb_3.jpg",
        "./assets/images/kravchenko/thumb_4.jpg"],
      images: ["./assets/images/kravchenko/elena_9.jpg",
        "./assets/images/kravchenko/elena_1.jpg",
        "./assets/images/kravchenko/elena_2.jpg",
        "./assets/images/kravchenko/elena_3.jpg",
        "./assets/images/kravchenko/elena_4.jpg",
        "./assets/images/kravchenko/elena_5.jpg",
        "./assets/images/kravchenko/elena_6.jpg",
        "./assets/images/kravchenko/elena_7.jpg",
        "./assets/images/kravchenko/elena_8.jpg"]
    },
    interview: "M8r98XLfk4g",
    youtube: "ZQzMCEtFoeY",
    collegues: "vTjm4Z6S1us",
    shortBiography: "<b>кандидат биологических наук</b><br>начальник Сектора молекулярной генетики клетки",
    biography: "<ul><li>Родилась в&nbsp;Москве.</li><li>Окончила МГУ им. М.&nbsp;В.&nbsp;Ломоносова по&nbsp;специальности генетика.</li><li>В&nbsp;2005 году защитила диссертацию по&nbsp;теме &laquo;Роль gypsy инсулятора в&nbsp;процессах трансвекции у&nbsp;D. melanogaster&raquo;.</li><li>Руководитель проекта Dsup (Damage suppressor) в&nbsp;ЛЯП ОИЯИ.</li></ul>",
    interestInScience: "Мне сильно повезло, что я&nbsp;застала окончание эпохи советских образовательных передач. В&nbsp;одной из&nbsp;них разбиралась тема из&nbsp;генетики: почему сиамская кошка выглядит как сиамская кошка. Там очень красивый механизм, который до&nbsp;сих пор приводит меня в&nbsp;полный восторг: окраска сиамской кошки зависит от&nbsp;того, как работает определенный ген. <...> Я&nbsp;была настолько поражена красотой этого решения, красотой этой генетической программы, что поняла: я&nbsp;хочу заниматься только этим. Собственно, главный интерес был заложен тогда. Я&nbsp;захотела понимать, как работают генетические программы, как ими управлять и&nbsp;как создавать собственные.",
    familyAndWork: "",
    experiments: 'Кандидат биологических наук, старший научный сотрудник ЛЯП ОИЯИ <b>Елена Кравченко</b>&nbsp;&mdash; выпускница биологического факультета МГУ. В&nbsp;2005 году она защитила диссертацию по&nbsp;теме &laquo;Роль gypsy инсулятора в&nbsp;процессах трансвекции у&nbsp;D.&nbsp;melanogaster&raquo;. В&nbsp;ОИЯИ Елена Владимировна возглавляет Сектор молекулярной генетики клетки ЛЯП ОИЯИ и&nbsp;руководит проектом Dsup (Damage suppressor).<br><br>Сектор Е.&nbsp;В. Кравченко сейчас занимается тремя направлениями исследований: изучением свойств уникальных белков тихоходок, а&nbsp;также созданием модельных организмов, продуцирующих такие белки; анализом влияния пониженного радиационного фона на&nbsp;модельные организмы (совместно с&nbsp;ИЯИ&nbsp;РАН на&nbsp;базе Баксанской нейтринной обсерватории); биомониторингом Байкала&nbsp;&mdash; наблюдением за&nbsp;показателями загрязнения вод озера тяжелыми металлами (совместно с&nbsp;ЛНФ ОИЯИ).',
    difficulties: "",
    hobbies: "Я&nbsp;очень люблю читать, у&nbsp;меня довольно большая библиотека. Я&nbsp;люблю гулять и&nbsp;люблю пить чай. Еще я&nbsp;очень люблю фотографировать грибы и&nbsp;выкладывать фото в&nbsp;<a class='link' target='_blank' rel='nofollow' style='text-decoration: none; color: #a9a1a1; transition: color .3s ease;' href='https://www.facebook.com/elena.v.kravchenko'>Facebook</a>. Я&nbsp;грибы не&nbsp;собираю, не&nbsp;готовлю, мне просто нравится фиксировать красоту этих творений природы.",
    wishes: 'Надо быть в&nbsp;первую очередь честным с&nbsp;собой. Нужно точно понимать, можешь&nbsp;ли ты&nbsp;сделать что-то реальное для науки. Я&nbsp;для себя поставила вопрос так: если я&nbsp;пойму, что не&nbsp;смогу сделать ничего важного, ничего интересного и&nbsp;не&nbsp;смогу соответствовать уровню, который я&nbsp;считаю достойным, то&nbsp;я&nbsp;уйду. И&nbsp;я&nbsp;бы хотела всем посоветовать быть честным с&nbsp;собой и&nbsp;понимать, нужны&nbsp;ли они науке, а&nbsp;не&nbsp;только нужна&nbsp;ли наука&nbsp;им.',
    time: {
      interestInScience: '01:48',
      carierStart: '',
      familyAndWork: '',
      experiments: '',
      difficulties: '',
      hobbies: '00:41',
      perfectDay: '',
      wishes: '01:32',
    },
    timeCode: {
      interestInScience: '22',
      carierStart: '',
      familyAndWork: '',
      experiments: '1447',
      difficulties: '',
      hobbies: '2657',
      perfectDay: '3081',
      wishes: '3214',
    }
  }, {
    fullName: "Маргарита Александрова, биолог",
    name: "Маргарита Васильевна Александрова",
    img_src: "./assets/images/alexandrova/alexandrova.jpg",
    images: {
      experiments: "./assets/images/alexandrova/experiments.jpg",
      thumbs: ["./assets/images/alexandrova/thumb_1.jpg",
        "./assets/images/alexandrova/thumb_2.jpg",
        "./assets/images/alexandrova/thumb_3.jpg",
        "./assets/images/alexandrova/thumb_4.jpg"],
      images: ["./assets/images/alexandrova/margarita_9.jpg",
        "./assets/images/alexandrova/margarita_1.jpg",
        "./assets/images/alexandrova/margarita_2.jpg",
        "./assets/images/alexandrova/margarita_3.jpg",
        "./assets/images/alexandrova/margarita_4.jpg",
        "./assets/images/alexandrova/margarita_5.jpg",
        "./assets/images/alexandrova/margarita_6.jpg",
        "./assets/images/alexandrova/margarita_7.jpg",
        "./assets/images/alexandrova/margarita_8.jpg"]
    },
    interview: "mDYxJWwO69w",
    youtube: "ZQzMCEtFoeY",
    collegues: "QLIa3cIy-94",
    shortBiography: "<b>кандидат биологических наук</b><br>старший научный сотрудник ЛЯП ОИЯИ",
    biography: "<ul><li>Родилась в&nbsp;городе Беково Пензенской области.</li><li>Окончила Пензенский политехнический институт по&nbsp;специальности измерительные приборы.</li><li>В&nbsp;1990 году защитила диссертацию по&nbsp;специальности радиобиология &laquo;Распределение умеренных повторов и&nbsp;сайтов радиационного мутагенеза в&nbsp;геноме Drosophila melanogaster&raquo;.</li><li>Участник проекта &laquo;Радиоген&raquo; и&nbsp;других проектов по&nbsp;молекулярной генетике РФФИ, Минобрнауки и&nbsp;Государственной программы &laquo;Приоритетные направления генетики&raquo;.</li></ul>",
    experiments: 'Кандидат биологических наук, старший научный сотрудник ЛЯП ОИЯИ <b>Маргарита Васильевна Александрова</b> закончила Пензенский политехнический институт. В&nbsp;1990&nbsp;году защитила диссертацию по&nbsp;теме &laquo;Распределение умеренных повторов и&nbsp;сайтов радиационного мутагенеза в&nbsp;геноме Drosophila melanogaster&raquo;.<br><br>Работает в&nbsp;Группе молекулярной и&nbsp;радиационной генетики ЛЯП ОИЯИ. На&nbsp;плечах Маргариты Васильевны лежит выполнение основных задач в&nbsp;проекте &laquo;Радиоген&raquo;, в&nbsp;молекулярно-генетических экспериментах, поддержанных грантами РФФИ, Минобрнауки и&nbsp;Госпрограммы &laquo;Приоритетные направления генетики&raquo;.',
    interestInScience: "",
    familyAndWork: "",
    difficulties: "",
    hobbies: "Летом мы&nbsp;живем на&nbsp;даче. Там у&nbsp;нас растут деревья, кустарники, газон, вот там мы&nbsp;отдыхаем. Это наше любимое место отдыха. А&nbsp;мое любимое занятие&nbsp;&mdash; выращивать розы. Огородом я&nbsp;не&nbsp;занимаюсь.",
    wishes: 'Начнем с&nbsp;приятного: с&nbsp;радости. Радости познания. Если интерес узнать что-то новое есть, не&nbsp;важно, какая это наука, тогда в&nbsp;науку идти надо. Если интереса нет&nbsp;&mdash; подожди, займись каким-то другим делом. &lt; ... &gt; И&nbsp;жизнь менять не&nbsp;бойтесь. Иногда это приносит очень много радости и&nbsp;положительных эмоций. И, главное, результат.',
    time: {
      interestInScience: '',
      carierStart: '',
      familyAndWork: '',
      experiments: '',
      difficulties: '',
      hobbies: '00:24',
      perfectDay: '',
      wishes: '01:16',
    },
    timeCode: {
      interestInScience: '',
      carierStart: '269',
      familyAndWork: '',
      experiments: '1726',
      difficulties: '',
      hobbies: '2778',
      perfectDay: '3102',
      wishes: '3354',
    }
  }, {
    fullName: "Дания Зинатулина, физик",
    name: "Дания Зинатулина",
    img_src: "./assets/images/zinatulina/zinatulina.jpg",
    images: {
      experiments: "./assets/images/zinatulina/experiments.jpg",
      thumbs: ["./assets/images/zinatulina/thumb_1.jpg",
        "./assets/images/zinatulina/thumb_2.jpg",
        "./assets/images/zinatulina/thumb_3.jpg",
        "./assets/images/zinatulina/thumb_4.jpg"],
      images: ["./assets/images/zinatulina/dania_8.jpg",
        "./assets/images/zinatulina/dania_1.jpg",
        "./assets/images/zinatulina/dania_2.jpg",
        "./assets/images/zinatulina/dania_3.jpg",
        "./assets/images/zinatulina/dania_4.jpg",
        "./assets/images/zinatulina/dania_5.jpg",
        "./assets/images/zinatulina/dania_6.jpg",
        "./assets/images/zinatulina/dania_7.jpg",
        "./assets/images/zinatulina/dania_9.jpg"]
    },
    interview: "DxRfq-Ldh1Q",
    youtube: "ZQzMCEtFoeY",
    collegues: "4Y9hssKffH8",
    shortBiography: "<b>кандидат физико-математических наук</b><br>старший научный сотрудник ЛЯП ОИЯИ",
    biography: "<ul><li>Родилась в&nbsp;городе Навои (Узбекистан).</li><li>Окончила Воронежский государственный университет (специализация&nbsp;&mdash; медицинская физика).</li><li>В&nbsp;2019 году защитила диссертацию по&nbsp;теме &laquo;Исследование мюонного захвата для двойного бета-распада&raquo;.</li><li>Руководитель проекта MONUMENT (PSI, Швейцария), участник проектов LEGEND/GERDA и&nbsp;DANSS.</li><li>Двое детей.</li></ul>",
    interestInScience: "Такой толчок мне дал мой дедушка. Он&nbsp;показал мне, что наша жизнь невозможна без физики. Дедушка был начальником одной из&nbsp;строек <span class='tooltip-element' style='border-bottom: 1px dotted; cursor: pointer;' data-tooltip='Министерство среднего машиностроения СССР (Минсредмаш СССР, МСМ СССР; разговорное Средмаш)'>Средмаша</span>, имел два образования и&nbsp;очень любил и&nbsp;физику, и&nbsp;математику. Когда однажды я&nbsp;принесла из&nbsp;школы тройку по&nbsp;физике, дедушка был совершенно обескуражен. Я&nbsp;ему объяснила, что не&nbsp;понимаю предмет. И&nbsp;вот в&nbsp;течение недели, пока длились каникулы, мы&nbsp;каждый день садились, открывали школьный учебник, и&nbsp;дедушка объяснял мне всё, что было непонятно. &laquo;Залог твоего успеха,&nbsp;&mdash; говорил дедушка,&nbsp;&mdash; знать материал наперед&raquo;. Я&nbsp;стала применять этот метод на&nbsp;практике. Пошли пятерки, а&nbsp;главное&nbsp;&mdash; пришло понимание физики.",
    familyAndWork: "<b>Дания Зинатулина</b> благодарна за&nbsp;поддержку мужу, а&nbsp;еще маме и&nbsp;брату, которые всегда приходят на&nbsp;помощь семье с&nbsp;двумя детьми. У&nbsp;Дании сложный рабочий график с&nbsp;поздними совещаниями и&nbsp;длительными командировками. Семья помогает Дании, и она чувствует себя счастливой и&nbsp;дома, и&nbsp;на&nbsp;работе.",
    experiments: 'Кандидат физико-математических наук, старший научный сотрудник Сектора слабых взаимодействий Научно-экспериментального отдела ядерной спектроскопии и&nbsp;радиохимии <b>Дания Зинатулина</b> окончила Воронежский государственный университет по&nbsp;специальности медицинская физика. В&nbsp;2019 году защитила диссертацию по&nbsp;теме &laquo;Исследование мюонного захвата для двойного бета-распада&raquo;.<br><br>Она руководит международным проектом MONUMENT (PSI, Швейцария) (измерение обычного мюонного захвата на&nbsp;нескольких изотопах) и&nbsp;участвует в&nbsp;экспериментах LEGEND/GERDA (поиск безнейтринного двойного бета-распада) и&nbsp;DANSS (исследование реакторных антинейтрино).',
    difficulties: "",
    hobbies: "Я&nbsp;хожу в&nbsp;бассейн, очень люблю бассейн, занимаюсь с&nbsp;тренером. Вода очень помогает, когда надо подумать, настроиться, переключиться. Еще я&nbsp;могу пойти на&nbsp;тренировку, позаниматься и&nbsp;там оставить то&nbsp;напряжение, которое получила на&nbsp;работе, а&nbsp;потом уже идти домой.",
    wishes: 'У&nbsp;человека должен быть интерес. Выделить направления и&nbsp;попробовать&nbsp;их. А&nbsp;когда человек выбрал направление и&nbsp;идет вперед, то&nbsp;никогда не&nbsp;сдаваться. Иногда человеку необходимы трудности, чтобы пойти дальше. Необходимо преодоление, чтобы начать видеть шире. И&nbsp;советую не&nbsp;уходить в&nbsp;узкие направления, надо пробовать разное, искать себя. Пробовать разное и&nbsp;не&nbsp;сдаваться.',
    time: {
      interestInScience: '01:12',
      carierStart: '',
      familyAndWork: '02:31',
      experiments: '',
      difficulties: '',
      hobbies: '01:24',
      perfectDay: '',
      wishes: '02:20',
    },
    timeCode: {
      interestInScience: '195',
      carierStart: '',
      familyAndWork: '701',
      experiments: '1856',
      difficulties: '',
      hobbies: '2694',
      perfectDay: '3163',
      wishes: '3572',
    }
  }
];
