export interface Heroine {
  fullName: string,
  name: string,
  img_src: string,
  images: {
    experiments: string,
    thumbs: string[],
    images: string[],
  },
  interview: string,
  youtube: string,
  collegues: string,
  shortBiography: string,
  biography: string,
  interestInScience: string,
  familyAndWork: string,
  experiments: string,
  difficulties: string,
  hobbies: string,
  wishes: string,
  time: {
    interestInScience: string,
    carierStart: string,
    familyAndWork: string,
    experiments: string,
    difficulties: string,
    hobbies: string,
    perfectDay: string,
    wishes: string,
  },
  timeCode: {
    interestInScience: string,
    carierStart: string,
    familyAndWork: string,
    experiments: string,
    difficulties: string,
    hobbies: string,
    perfectDay: string,
    wishes: string,
  }
}
